spring:
  application:
    name: hello-spring-cloud-web-addUserToDB-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8764

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/